# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OKbUyEmNAS69RLlED6iU5QqiMsWir1F
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,3,6,9,12,15,18])
y=np.array([0,3,6,9,12,15,18])
mycolor=['red','green','purple','lime','aqua','yellow','blue']
size=[30,60,90,120,150,180,210]

plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['510','613','614','615','616','617'])
y=np.array([18,21,17,19,22,25])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['510','613','614','615','616','617'])
y=np.array([18,21,17,19,22,25])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,15,22,20,8])
mylabels=["Mercedes-Benz","Rolls-Roys","BMW ","Bugatti","Audi"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,15,22,20,8])
mylabels=["Mercedes-Benz","Rolls-Roys","BMW ","Bugatti","Audi"]
myexplode=[0,0,0,0,0.3]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,15,22,20,8])
mylabels=["Mercedes-Benz","Rolls-Roys","BMW ","Bugatti","Audi"]

plt.pie(x,labels=mylabels)
plt.legend()
plt.show()